tasks:

  - name: cdk
    before: |
      npm i -g aws-cdk
  - name: terraform
    before: |
      ./bin/terraform-cli-install.sh

  - name: utils
    before: |
      sudo apt-get install tree
      #powershell for aws
      #https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
  - name: powershell
    before: |
      ./bin/powershell-cli-install.sh

  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: ./bin/aws-cli-install.sh

    

