#!/usr/bin/env bash

#check if the argumet is provided

if [ -z "$1" ]; then
  echo "❌ Error: No argument provided."
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "❌ Error: No argument provided."
else
  export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "❌ Error: No argument provided."
else
  export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "❌ Error: No argument provided."
else
  export ASSOC_ID="$4"
fi

if [ -z "$5" ]; then
  echo "❌ Error: No argument provided."
else
  export RT_ID="$5"
fi


# detach the IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete the IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

#delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID


#desassociate route table
#aws ec2 disassociate-route-table --association-id $ASSOC_ID


#delete route table
#aws ec2 delete-route-table --route-table-id $RT_ID

# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID


