#!/usr/bin/env bash
echo "Create Bucket"

# check if bucket name is provided
if [ -z "$1" ]; then
  echo "Error: No bucket name provided."
  exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--query Location \
--output text
#--create-bucket-configuration="LocationConstraint=us-west-1"