#!/usr/bin/env bash

echo "Delete Objects"

#check if bucket name
if [ -z "$1" ]; then
  echo "Error: No bucket name provided."
  exit 1
fi


BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json