#!/usr/bin/env bash

echo "List Object"

# check if bucket name is provided
if [ -z "$1" ]; then
  echo "Error: No bucket name provided."
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket $BUCKET_NAME