#!/usr/bin/env bash

echo "Put Object"

#check if bucket name
if [ -z "$1" ]; then
  echo "Error: No bucket name provided."
  exit 1
fi

#check for filename prefix
if [ -z "$2" ]; then
  echo "Error: No filename."
  exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2

OBJECT_KEY=$(basename "$FILE_NAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILE_NAME \
--key $OBJECT_KEY