#!/usr/bin/env bash

echo "Deploy s3 bucket via CFM"

STACK_NAME="cfm-s3-simples"

aws cloudformation deploy \
--template-file template.yaml \
--region us-east-1 \
--no-execute-changeset \
--stack-name $STACK_NAME
